// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmxyqovesafljrrfqalb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxteHlxb3Zlc2FmbGpycmZxYWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjI5NzMsImV4cCI6MjA2MzU5ODk3M30.ducZePLYiB7xZ09VOnt5cAj42T66TZ8lYF1yW_-4FU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);